Разметка главной страницы
htmlacademy-htmlcss/1876843-device-32 pull request #2
Opened 2021-09-27 00:19 UTC by yaslipa

Разметка главной страницы готова, жду разбора полетов.

2021-09-27 19:04 UTC, alexjavascript commented on index.html
> +    <!-- HEADER -->
Очевидные комментарии по большей части будут загрязнять твой код, а не служить упрощением для понимания

2021-09-27 19:05 UTC, alexjavascript commented on index.html
> +      <a class="page-header__logo"><img src="" alt="Логотип Девайс"></a>
Необходимо добавить текст На главную внутри ссылки, в будущем ты его визуально скроешь

2021-09-27 19:06 UTC, alexjavascript commented on index.html
> +          <h2 class="visually-hidden">Поиск по сайту</h2>
form search в nav может не содержать дополнительный заголовок

2021-09-27 19:08 UTC, alexjavascript commented on index.html
> +          <h3 class="slider__title">Порхает как бабочка,<br>жалит как пчела!</h3>
Эта фраза не имеет семантического веса, в заголовок нужно добавить название товара

2021-09-27 19:08 UTC, alexjavascript commented on index.html
> +          <dl class="slider__details">
Было бы хорошо добавить заголовок Характеристики

2021-09-27 19:16 UTC, alexjavascript commented on index.html
> +          <h2 class="visually-hidden">Поиск по сайту</h2>
В формы мы не ставим заголовки

2021-09-27 19:17 UTC, alexjavascript commented on index.html
> +        <h2 class="visually-hidden">Разделы каталога</h2>
Категории

2021-09-27 19:17 UTC, alexjavascript commented on index.html
> +          <dd class="features__descr">
Напиши мне пожалуйста, почему именно этот тег ты хочешь использовать здесь

2021-09-27 19:18 UTC, alexjavascript commented on index.html
> +      <button class="delivery-btn" type="button">Доставим редкий товар под заказ</button>
Ссылка

2021-09-27 19:27 UTC, alexjavascript requested changes
Необходимы исправления

2021-09-27 20:16 UTC, yaslipa commented on index.html
> +      <a class="page-header__logo"><img src="" alt="Логотип Девайс"></a>
Я думала добавить текст ссылки и атрибут **href** уже на внутреннюю (страницу каталога). На главной, по идее, просто лого, ссылка не активна.

2021-09-27 23:04 UTC, yaslipa commented on index.html
> +      <button class="delivery-btn" type="button">Доставим редкий товар под заказ</button>
В макете есть модальное окно "Доставка под заказ" — я предполагала, что оно появляется при клике на эту кнопку.

2021-09-27 23:08 UTC, yaslipa commented on index.html
> +          <dd class="features__descr">
Мне кажется, по семантике подходит. Это список с тремя определениями и их расшифровкой.

2021-09-29 13:09 UTC, alexjavascript commented on index.html
> +      <a class="page-header__logo"><img src="" alt="Логотип Девайс"></a>
Это плохой UX, ссылку нужно добавить

2021-09-29 13:11 UTC, alexjavascript commented on index.html
> +          <dd class="features__descr">
Окей, хорошо

2021-09-29 13:13 UTC, alexjavascript commented on index.html
> +      <button class="delivery-btn" type="button">Доставим редкий товар под заказ</button>
Без js необходимую информацию не получим, поэтому нужно иметь ссылку как возможность перейти на другую страницу

2021-09-29 19:13 UTC, merged